Softrend: works only with X11
reicast/reicast-emulator pull request #1373
Opened 2018-09-04 17:09 UTC by baka0815

If X11 support is not there, reicast doesn't compile because the softrenderer needs it.
Use #ifdef to do X11 only if SUPPORT_X11 is set.

2018-09-04 18:00 UTC, dmiller423 commented
yes I believe the only support w.o X11 is GLES on EGL

2018-09-04 18:04 UTC, dmiller423 reviewed
You might consider using #elif instead of another ifdef as well as another else afterwards w. a #error since you're effectively turning it into not rendering anything...  Is this even useful?   we could just do a 
#if defined(NO_X11) && defined(SOFTREND)  
#error can't use softrend w.o X11   
#endif

2018-09-04 18:19 UTC, baka0815 commented
We could do that, however we would also need to disable SOFTREND on SDL then.

2018-09-04 18:42 UTC, baka0815 commented
After confirming that GLES still renders (however without GUI on Linux) and SDL still working, I went for the ``#else`` route because we might add additional software outputs (like SDL) in the future.

2018-09-04 18:54 UTC, dmiller423 requested changes
1211: #elif defined(SUPPORT_X11)
1212: delete 
1229: remove indent
1232: delete

2018-09-04 18:56 UTC, dmiller423 commented
SDL w.o X11?   what's it use directfb ?

2018-09-04 19:01 UTC, baka0815 commented
SDL uses GLES or OpenGL:
https://github.com/reicast/reicast-emulator/blob/1c880fc37c64b3dd1d79df1f5d90275ed1a6ef02/core/sdl/sdl.cpp#L463

2018-09-04 19:05 UTC, dmiller423 commented
Without X11?

2018-09-04 19:07 UTC, baka0815 commented
At least without the X11 define, yes. SDL should also work (theoretically) on wayland.
If you build SDL with X11, you'll get two windows (X11 and SDL) however only the SDL one renders.

2018-09-04 19:39 UTC, dmiller423 approved these changes

2018-09-04 19:42 UTC, merged

2018-09-04 19:42 UTC, dmiller423 commented
lmao,  the define is to control whether or not to use X11 directly ... the question refers to whether or not SDL currently works on linux w.o any X11/Xorg ( aka direct from console ) ...   
Either way the changes amount to nothing more than a #ifdef/error, albeit one more informative than the other error message...  I will merge it and close.

2018-09-04 19:45 UTC, baka0815 commented
Sorry, I didn't get you. Yes, it *doesn't* work without any graphical backend like X11.
So X11 (or similar) is necessary.

2019-09-14 03:43 UTC, mrfixit2001 commented
Well, it USED to work fine without x11... not it won't even compile without it :(