Add bios autoboot option
reicast/reicast-emulator pull request #1798
Opened 2020-02-12 07:48 UTC by Cpasjuste

This PR allow booting directly to the bios by giving the "bios" arg instead an image file.

2020-02-12 07:49 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/reicast/reicast-emulator?pullRequest=1798) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/reicast/reicast-emulator?pullRequest=1798) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/reicast/reicast-emulator?pullRequest=1798) it.</sub>

2020-02-12 12:05 UTC, skmp requested changes

2020-02-12 12:05 UTC, skmp commented on libswirl/gui/gui.cpp
> +                if(game_file == "bios")
Do you mind adjusting the logic in `libswirl.cpp::int GetFile(char* szFileName)`? You'll have to change a few empty strings as well in GUI, but it's a much cleaner solution to make "bios" mean "bios" at the core level. I never liked using an empty string anyway.

2020-02-12 12:29 UTC, skmp commented on libswirl/gui/gui.cpp
> +                if(game_file == "bios")
Hmm, also maybe name it no "nodisk" to make it clear what it does?

2020-02-25 21:33 UTC, baka0815 requested changes
@Cpasjuste you should add a parameter ``-bios``/``--bios`` (or ``-nodisk``/``--nodisk``) like in line 127 of cl.cpp instead of using "bios" as a magic value for a disk image.

2020-03-02 14:30 UTC, skmp commented
@baka0815 I don't mind using a special value for no disk, but I'd rather it be "nodisk" than "bios". Command line arguments aren't settable from the cfg file, that's why I try to keep them at a minimum

2020-03-04 10:39 UTC, skmp commented
functionality merged via #1818

2020-03-04 10:39 UTC, closed without merging